In [18]:
import pandas as pd
s=pd.read_csv("Spam.csv")
s

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [19]:
s["spam"]=s["Category"].apply(lambda x:1 if x=="spam" else 0)

In [20]:
s

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [21]:
s["spam"].isnull().any()

False

In [22]:
s.drop("Category",axis=1,inplace=True)

In [23]:
s

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [24]:
print(type(s[["Message"]]))

<class 'pandas.core.frame.DataFrame'>


In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(s["Message"],s.spam,test_size=0.25)

In [26]:
print(x_train.shape)

(4179,)


In [27]:
x_train.values

array(['Tell rob to mack his gf in the theater',
       "U wan 2 haf lunch i'm in da canteen now.",
       'Haha better late than ever, any way I could swing by?', ...,
       'Have a lovely night and when you wake up to see this message, i hope you smile knowing all is as should be. Have a great morning',
       'We tried to contact you re your reply to our offer of 750 mins 150 textand a new video phone call 08002988890 now or reply for free delivery tomorrow',
       'YOU ARE CHOSEN TO RECEIVE A £350 AWARD! Pls call claim number 09066364311 to collect your award which you are selected to receive as a valued mobile customer.'],
      dtype=object)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
d=cv.fit_transform(x_train.values)
print(x_train.values.shape)
print(d.shape)
print(d.toarray())

(4179,)
(4179, 7451)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [29]:
print(pd.DataFrame(d.toarray()).columns)

RangeIndex(start=0, stop=7451, step=1)


In [30]:
print(y_train.shape)

(4179,)


In [31]:
from sklearn.naive_bayes import MultinomialNB
bn= MultinomialNB()
bn.fit(d.toarray(),y_train)

MultinomialNB()

In [32]:
email=["10% discount buy offer immediatly"]

In [34]:
import numpy as np
gh=np.array(email)
gh.shape




(1,)

In [35]:
djbravo=cv.transform(np.array(email))

In [36]:
y=djbravo.toarray()
y

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
y.shape

(1, 7451)

In [38]:
bn.predict(y)

array([1], dtype=int64)

In [39]:
x_test1=cv.transform(x_test.values)


In [40]:
bn.score(x_test1,y_test)


0.9899497487437185

In [41]:
import pickle
with open("Spam_filter.pickle","wb") as pt:
    pickle.dump(bn,pt)